"""add_image_url

Revision ID: 09c0881f7046
Revises: c0980b25cabb
Create Date: 2026-07-12 13:02:14.707691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c0881f7046'
down_revision: Union[str, None] = 'c0980b25cabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'departments', 'users', ['head_id'], ['id'], use_alter=True)
    op.add_column('maintenance_requests', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maintenance_requests', 'image_url')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('assets', 'image_url')
    # ### end Alembic commands ###
